# My bash config

# fix for QMK
# Python PIP
export PATH="$HOME/.local/bin:$PATH"

# RB Env
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# GD fix http://www.sane-project.org/
export SANE_USB_WORKAROUND=1

# ls replacement
alias ll='exa -l  --time-style=iso --git --icons --group-directories-first'
alias la='exa -la --time-style=iso --git --icons --group-directories-first'
alias l='exa      --time-style=iso --git --icons --group-directories-first'

# for fast audio downloads
alias youtube-dl-audio='youtube-dl --ignore-errors --output "%(title)s.%(ext)s" --extract-audio --audio-format mp3'

# Rust config
source "$HOME/.cargo/env"

# fzf completion for command history
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Modern shell prompt 
eval "$(starship init bash)"

# Jump fast between directories
eval "$(zoxide init bash --cmd j)"

# Browse large directories
#source /home/greg/.config/broot/launcher/bash/br

# Alacritty
#source ~/.bash_completion.d/alacritty


